services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: php-fpm
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    image: nginx_app
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
